# Generated by Django 5.1.3 on 2024-11-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_rule_company_ruleset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleset',
            name='rules',
            field=models.TextField(),
        ),
    ]
